version: '3'
services:
  prisma-postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
  typeorm-postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=typeorm
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  mysql:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    volumes:
      - /var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - 5672:5672
      - 15672:15672
